# Generated by Django 5.2.4 on 2025-08-07 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticabd', '0002_userprofile_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='user_datasets/')),
                ('file_size', models.BigIntegerField()),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('numeric_columns', models.IntegerField()),
                ('categorical_columns', models.IntegerField()),
                ('missing_values_percentage', models.FloatField(default=0.0)),
                ('duplicate_rows', models.IntegerField(default=0)),
                ('outliers_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('missing_count', models.IntegerField(default=0)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('std_dev', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('q25', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('q75', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('unique_values', models.IntegerField(blank=True, null=True)),
                ('most_common_value', models.CharField(blank=True, max_length=255, null=True)),
                ('most_common_count', models.IntegerField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='analyticabd.userdataset')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
