# Generated by Django 5.2.4 on 2025-08-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticabd', '0003_userdataset_datasetvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetvariable',
            name='outliers_count',
            field=models.IntegerField(default=0),
        ),
    ]
