# Generated by Django 5.2.4 on 2025-08-08 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticabd', '0007_reportdocument_reportsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('ai', 'AI Response')], max_length=20)),
                ('content', models.TextField()),
                ('is_added_to_report', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_message', to='analyticabd.reportsection')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='analyticabd.analysissession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
