# Generated by Django 5.2.4 on 2025-08-08 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticabd', '0008_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_users', to='analyticabd.analysissession'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='ui_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
