# Generated by Django 5.2.4 on 2025-08-08 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticabd', '0009_userpreference_current_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='current_session',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='ui_state',
        ),
        migrations.CreateModel(
            name='DatasetUIState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_state_for_dataset', to='analyticabd.analysissession')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_states', to='analyticabd.userdataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_ui_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'dataset')},
            },
        ),
    ]
