# Generated by Django 5.2.4 on 2025-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticabd', '0011_billingsetting_subscriptionplan_tokenusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
